/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CamadaW;

import CamadaS.PrincipalS;

/**
 *
 * @author Luis
 */
public class PrincipalW extends javax.swing.JFrame {

    private final PrincipalS controlador;
    /**
     * Creates new form Principal
     */
    public PrincipalW() {
        initComponents();
        controlador = new PrincipalS(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMov = new javax.swing.JMenu();
        jMenuItemDep = new javax.swing.JMenuItem();
        jMenuItemRet = new javax.swing.JMenuItem();
        jMenuItemTrans = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemClienteAdd = new javax.swing.JMenuItem();
        jMenuItemContaAdd = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemRM = new javax.swing.JMenuItem();
        jMenuItemRP = new javax.swing.JMenuItem();
        jMenuItemRC = new javax.swing.JMenuItem();
        jMenuConfig = new javax.swing.JMenu();
        jMenuItemClienteEdit = new javax.swing.JMenuItem();
        jMenuItemContaEdit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuMov.setText("Movimentações");

        jMenuItemDep.setText("Deposito");
        jMenuItemDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDepActionPerformed(evt);
            }
        });
        jMenuMov.add(jMenuItemDep);

        jMenuItemRet.setText("Retirada");
        jMenuItemRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRetActionPerformed(evt);
            }
        });
        jMenuMov.add(jMenuItemRet);

        jMenuItemTrans.setText("Transferencia");
        jMenuItemTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransActionPerformed(evt);
            }
        });
        jMenuMov.add(jMenuItemTrans);

        jMenuBar1.add(jMenuMov);

        jMenuCadastro.setText("Cadastros");

        jMenuItemClienteAdd.setText("Cliente");
        jMenuItemClienteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteAddActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemClienteAdd);

        jMenuItemContaAdd.setText("Conta");
        jMenuItemContaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContaAddActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemContaAdd);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorio.setText("Relatórios");

        jMenuItemRM.setText("Relatório Movimentação");
        jMenuItemRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRMActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemRM);

        jMenuItemRP.setText("Relatório Clientes");
        jMenuItemRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRPActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemRP);

        jMenuItemRC.setText("Relatório Contas");
        jMenuItemRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRCActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemRC);

        jMenuBar1.add(jMenuRelatorio);

        jMenuConfig.setText("Configurações");

        jMenuItemClienteEdit.setText("Cliente");
        jMenuItemClienteEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteEditActionPerformed(evt);
            }
        });
        jMenuConfig.add(jMenuItemClienteEdit);

        jMenuItemContaEdit.setText("Conta");
        jMenuItemContaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContaEditActionPerformed(evt);
            }
        });
        jMenuConfig.add(jMenuItemContaEdit);

        jMenuBar1.add(jMenuConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDepActionPerformed
        controlador.AbrirDeposito();
    }//GEN-LAST:event_jMenuItemDepActionPerformed

    private void jMenuItemClienteAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteAddActionPerformed
        controlador.AbrirCadastroCliente();
    }//GEN-LAST:event_jMenuItemClienteAddActionPerformed

    private void jMenuItemClienteEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteEditActionPerformed
        controlador.AbrirAlteracaoCliente();
    }//GEN-LAST:event_jMenuItemClienteEditActionPerformed

    private void jMenuItemContaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContaAddActionPerformed
        controlador.AbrirCadastroConta();
    }//GEN-LAST:event_jMenuItemContaAddActionPerformed

    private void jMenuItemContaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContaEditActionPerformed
        controlador.AbrirAlteracaoConta();
    }//GEN-LAST:event_jMenuItemContaEditActionPerformed

    private void jMenuItemRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRPActionPerformed
        controlador.AbrirPesquisaCliente();
    }//GEN-LAST:event_jMenuItemRPActionPerformed

    private void jMenuItemRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRCActionPerformed
        controlador.AbrirPesquisaConta();
    }//GEN-LAST:event_jMenuItemRCActionPerformed

    private void jMenuItemRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRetActionPerformed
        controlador.AbrirRetirada();
    }//GEN-LAST:event_jMenuItemRetActionPerformed

    private void jMenuItemTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransActionPerformed
        controlador.AbrirTransferencia();
    }//GEN-LAST:event_jMenuItemTransActionPerformed

    private void jMenuItemRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRMActionPerformed
        controlador.abrirMovPesquisa();
    }//GEN-LAST:event_jMenuItemRMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuConfig;
    private javax.swing.JMenuItem jMenuItemClienteAdd;
    private javax.swing.JMenuItem jMenuItemClienteEdit;
    private javax.swing.JMenuItem jMenuItemContaAdd;
    private javax.swing.JMenuItem jMenuItemContaEdit;
    private javax.swing.JMenuItem jMenuItemDep;
    private javax.swing.JMenuItem jMenuItemRC;
    private javax.swing.JMenuItem jMenuItemRM;
    private javax.swing.JMenuItem jMenuItemRP;
    private javax.swing.JMenuItem jMenuItemRet;
    private javax.swing.JMenuItem jMenuItemTrans;
    private javax.swing.JMenu jMenuMov;
    private javax.swing.JMenu jMenuRelatorio;
    // End of variables declaration//GEN-END:variables
}
